"""empty message

Revision ID: ade3485ea8e2
Revises: 0be369b65da7
Create Date: 2025-04-23 15:44:12.312699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ade3485ea8e2'
down_revision = '0be369b65da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('last_login_ip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_ip', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True))
        batch_op.add_column(sa.Column('password_changed_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_login_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
